const FEATURED=[
{slug:'noir-motors',name:'NOIR MOTORWORKS',niche:'AUTOMOTIVE',desc:'Кінематографічний automotive-сайт із живим конфігуратором, темною металевою типографікою та рухом, що підкреслює швидкість.',motion:'float',glow:'#788b9f',tags:['ALL','AUTO']},
{slug:'atlas-residence',name:'ATLAS RESIDENCE',niche:'REAL ESTATE',desc:'Архітектурний сайт із великими просторовими паузами, м’якими переходами та логікою підбору резиденції.',motion:'tilt',glow:'#c8aa89',tags:['ALL','REAL ESTATE']},
{slug:'elan-clinic',name:'ÉLAN CLINIC',niche:'BEAUTY / CLINIC',desc:'Світла editorial-естетика, спокійний motion і чистий booking flow без відчуття шаблонної клініки.',motion:'drift',glow:'#e4c9bb',tags:['ALL','HEALTH']},
{slug:'sable-jewels',name:'SABLE',niche:'JEWELRY / COMMERCE',desc:'Предметна розкіш, ювелірна типографіка, configurator металу та композиція, що працює як fashion editorial.',motion:'float',glow:'#c7aa76',tags:['ALL','COMMERCE']},
{slug:'pulse-ai',name:'PULSE AI',niche:'SAAS / AI',desc:'Продуктовий сайт із живою UI-системою, data-motion, dashboard сценами та дуже чітким conversion flow.',motion:'tilt',glow:'#6e7cff',tags:['ALL','TECH']},
{slug:'nocturne',name:'NOCTURNE',niche:'HOSPITALITY',desc:'Темний ресторанний experience: відео-відчуття, резервація столу, меню як сцена і плавні нічні переходи.',motion:'drift',glow:'#8c2632',tags:['ALL','HOSPITALITY']},
{slug:'meridian-capital',name:'MERIDIAN CAPITAL',niche:'PRIVATE FINANCE',desc:'Сувора система для private capital: мінімалізм, ринкові дані, risk selector і відчуття інституційного бренду.',motion:'float',glow:'#a1b6a0',tags:['ALL','BUSINESS']},
{slug:'black-shield',name:'BLACK / SHIELD',niche:'CYBERSECURITY',desc:'Термінальний cyber-дизайн із live scan, сигнальною типографікою та інтерфейсом, схожим на командний центр.',motion:'tilt',glow:'#4cffb2',tags:['ALL','TECH']},
{slug:'helix-bio',name:'HELIX / BIO',niche:'BIOTECH',desc:'Науковий, але не холодний. Молекулярні модулі, pipeline selector і анімовані дослідницькі дані.',motion:'drift',glow:'#7fd6df',tags:['ALL','HEALTH']},
{slug:'nord-isles',name:'NORD ISLES',niche:'LUXURY TRAVEL',desc:'Подорож як журнал: великі фото, горизонтальні зміщення, itinerary-builder та відчуття приватної експедиції.',motion:'float',glow:'#81a6b7',tags:['ALL','TRAVEL']},
{slug:'field-office',name:'FIELD OFFICE',niche:'CREATIVE STUDIO',desc:'Антисітка, жорстка типографіка, нестандартні hover-сцени та портфоліо, що живе як арт-директорська дошка.',motion:'tilt',glow:'#ff704d',tags:['ALL','CREATIVE']},
{slug:'still-wellness',name:'STILL',niche:'WELLNESS',desc:'Тактильний wellness-сайт із дуже повільним motion, м’яким ритмом і booking flow без візуального шуму.',motion:'drift',glow:'#d8cdbd',tags:['ALL','HEALTH']}
];
const ARCHIVE=[
['atelier-mono','ATELIER MONO','FASHION'],['orbit-cloud','ORBIT CLOUD','SAAS'],['forge-club','FORGE CLUB','SPORT'],['nova-academy','NOVA ACADEMY','EDUCATION'],['veritas','VERITAS','LEGAL'],['solis-hotel','SOLIS HOTEL','HOTEL'],['echo-artist','ECHO / ARTIST','MUSIC'],['mimo-kids','MIMO KIDS','KIDS'],['common-ground','COMMON GROUND','CAFE'],['ratio','RATIO','ARCHITECTURE'],['nera-beauty','NERA BEAUTY','COMMERCE'],['white-room','WHITE ROOM','DENTAL'],['wild-routes','WILD ROUTES','TRAVEL'],['brick-form','BRICK / FORM','CONSTRUCTION'],['bark-care','BARK & CO.','VET'],['frame-studio','FRAME / 01','PHOTO'],['cuts','CUTS.','BARBER'],['northline','NORTHLINE','LOGISTICS'],['void-arena','VOID / ARENA','GAMING'],['bloom','BLOOM','EVENTS'],['greenhouse','GREENHOUSE','PLANTS'],['object-17','OBJECT / 17','DESIGN'],['obelisk','OBELISK','REAL ESTATE'],['mono-bank','MONO CAPITAL','FINTECH'],['aura-home','AURA HOME','INTERIOR'],['kinetic','KINETIC','AGENCY'],['terra','TERRA','FOOD'],['velvet','VELVET','BEAUTY'],['arc-lab','ARC LAB','ARCHITECTURE'],['north-coast','NORTH COAST','TRAVEL']
];
const filters=['ALL','AUTO','REAL ESTATE','HEALTH','COMMERCE','TECH','HOSPITALITY','BUSINESS','TRAVEL','CREATIVE'];
let active='ALL';
const f=document.getElementById('filters'),s=document.getElementById('showcase'),g=document.getElementById('archiveGrid');
filters.forEach(v=>{const b=document.createElement('button');b.textContent=v;b.className=v===active?'active':'';b.onclick=()=>{active=v;[...f.children].forEach(x=>x.classList.toggle('active',x===b));render()};f.appendChild(b)});
function chapter(p,i){return `<article class="chapter" data-motion="${p.motion}" style="--glow:${p.glow}"><div class="chapter-copy"><span>${String(i+1).padStart(2,'0')} / ${p.niche}</span><h2>${p.name}</h2><p>${p.desc}</p><div class="chapter-meta"><div><span>FORMAT</span><b>FULL WEBSITE</b></div><div><span>MOTION</span><b>${p.motion.toUpperCase()}</b></div><div><span>LIVE</span><b>INTERACTIVE</b></div></div><a href="/demo/${p.slug}" target="_blank">OPEN FULL SITE ↗</a></div><div class="device-stage"><div class="device-glow"></div><div class="laptop"><div class="screen"><iframe loading="lazy" tabindex="-1" src="/demo.html?site=${p.slug}&embed=1" title="${p.name} live website"></iframe></div><div class="base"></div></div></div></article>`};
function render(){const list=active==='ALL'?FEATURED:FEATURED.filter(p=>p.tags.includes(active));s.innerHTML=list.map(chapter).join('');observe()}
const palettes=[['#0b0b0d','linear-gradient(135deg,#25272b 0 40%,#090a0c 40%)'],['#e9e4d9','linear-gradient(130deg,#c9b399 0 35%,#f4efe5 35%)'],['#17201f','radial-gradient(circle at 70% 30%,#607b70,transparent 28%)'],['#1b1622','linear-gradient(90deg,#7b4c70 0 20%,transparent 20%)'],['#d8e0e4','linear-gradient(160deg,#89a8b8 0 35%,#eef1f2 35%)'],['#18110d','linear-gradient(130deg,#7f4f2d,#1a110d 55%)']];
g.innerHTML=ARCHIVE.map((a,i)=>{const p=palettes[i%palettes.length];return `<a class="archive-card" href="/demo/${a[0]}" target="_blank"><div class="mini-screen" style="--bg:${p[0]};--art:${p[1]}"></div><small>${String(i+13).padStart(2,'0')} / ${a[2]}</small><strong>${a[1]}</strong></a>`}).join('');
let io;function observe(){io?.disconnect();io=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('in',e.isIntersecting)),{threshold:.28});document.querySelectorAll('.chapter').forEach(el=>io.observe(el))}
render();